"""Official Python SDK for the Protoface API."""

from __future__ import annotations

from protoface_sdk._client import (
    DEFAULT_BASE_URL,
    OPERATION_COVERAGE,
    AvatarsResource,
    PipecatResource,
    PipecatSessionsResource,
    ProtofaceClient,
    SessionsResource,
    UsageResource,
)
from protoface_sdk.errors import (
    AuthenticationError,
    ConflictError,
    InternalError,
    InvalidRequestError,
    NotFoundError,
    PermissionError,
    ProtofaceConnectionError,
    ProtofaceError,
    QuotaExceededError,
    RateLimitError,
    ServiceUnavailableError,
    UnprocessableError,
)
from protoface_sdk.models import (
    TERMINAL_SESSION_STATUSES,
    ApiError,
    ApiErrorEnvelope,
    Avatar,
    AvatarStatus,
    ErrorType,
    LiveKitAudioSource,
    LiveKitTransportConfig,
    Page,
    PipecatRelayView,
    PipecatSessionCreateRequest,
    PipecatSessionView,
    PipecatTransportConfig,
    PipecatWebSocketRelayView,
    PlanView,
    QualityTier,
    Session,
    SessionCreateRequest,
    SessionFailure,
    SessionStatus,
    SessionUsage,
    StatusComponent,
    StatusResponse,
    TransportConfig,
    UsageSummary,
    WebSocketTransportConfig,
)

__version__ = "0.1.0"

__all__ = [
    "DEFAULT_BASE_URL",
    "OPERATION_COVERAGE",
    "TERMINAL_SESSION_STATUSES",
    "ApiError",
    "ApiErrorEnvelope",
    "AuthenticationError",
    "Avatar",
    "AvatarStatus",
    "AvatarsResource",
    "ConflictError",
    "ErrorType",
    "InternalError",
    "InvalidRequestError",
    "LiveKitAudioSource",
    "LiveKitTransportConfig",
    "NotFoundError",
    "Page",
    "PermissionError",
    "PipecatRelayView",
    "PipecatResource",
    "PipecatSessionCreateRequest",
    "PipecatSessionView",
    "PipecatSessionsResource",
    "PipecatTransportConfig",
    "PipecatWebSocketRelayView",
    "PlanView",
    "ProtofaceClient",
    "ProtofaceConnectionError",
    "ProtofaceError",
    "QualityTier",
    "QuotaExceededError",
    "RateLimitError",
    "ServiceUnavailableError",
    "Session",
    "SessionCreateRequest",
    "SessionFailure",
    "SessionStatus",
    "SessionUsage",
    "SessionsResource",
    "StatusComponent",
    "StatusResponse",
    "TransportConfig",
    "UnprocessableError",
    "UsageResource",
    "UsageSummary",
    "WebSocketTransportConfig",
    "__version__",
]
