# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class AvatarStatus(Enum):
    """
    Lifecycle of a custom avatar.

    `ready` — usable for sessions.
    `processing` — being fitted / converted.
    `failed` — fitting failed; will not be usable without re-upload.
    """

    ready = "ready"
    processing = "processing"
    failed = "failed"


class BodyCreateAvatar(BaseModel):
    image: str = Field(
        ...,
        description="Portrait image (PNG or JPEG).",
        json_schema_extra={"contentMediaType": "application/octet-stream"},
    )
    name: str | None = Field(default="Custom Avatar", description="Display name for the avatar.")
    runtime_type: str | None = Field(default="avtr1", description="Build stack. Default `avtr1`.")


class ErrorType(Enum):
    """
    Top-level error categories. Maps roughly to HTTP status.

    `code` (a free-form lower_snake_case string on `ApiError`) is the
    machine-readable subcode SDKs should switch on; `type` is the broad
    category.
    """

    invalid_request = "invalid_request"
    authentication = "authentication"
    permission = "permission"
    not_found = "not_found"
    conflict = "conflict"
    unprocessable = "unprocessable"
    rate_limit = "rate_limit"
    quota_exceeded = "quota_exceeded"
    internal = "internal"
    service_unavailable = "service_unavailable"


class LiveKitAudioSource(Enum):
    """
    How the LiveKit worker receives audio from the room.

    Use `data_stream` with the LiveKit Agents plugin. Use `track` only for
    custom integrations that publish audio tracks directly.
    """

    data_stream = "data_stream"
    track = "track"


class LiveKitTransportConfig(BaseModel):
    """
    BYO LiveKit transport.

    The customer owns the room and mints `worker_token`; we never touch
    their LiveKit API key or secret.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    audio_source: LiveKitAudioSource | None = Field(
        default=LiveKitAudioSource.data_stream,
        description="How the worker receives audio. See LiveKitAudioSource.",
    )
    room_name: str = Field(..., description="Name of the LiveKit room the worker should join.")
    subscribe_to_identity: str | None = Field(
        default=None,
        description="When `audio_source=track`, pin to this participant. Ignored otherwise.",
    )
    synthetic_audio_if_no_input: bool | None = Field(
        default=False,
        description="If True and no participant joins within 10 s, the worker falls back to a synthetic sine generator. Demo aid only; default off.",
    )
    type: Literal["livekit"] = "livekit"
    url: str = Field(..., description="Customer's LiveKit URL, e.g. `wss://my-app.livekit.cloud`.")
    worker_identity: str | None = Field(
        default="protoface-worker",
        description="Identity the worker presents inside the room.",
    )
    worker_token: str = Field(
        ...,
        description='Short-lived JWT the customer mints authorizing our worker to join the room. **Write-only.** Never echoed back on read; `GET /v1/sessions/{id}.transport.worker_token` returns the string `"[redacted]"`.',
    )


class MaxDurationSeconds(RootModel[int]):
    root: int = Field(..., ge=1, le=3600)


class PipecatTransportConfig(BaseModel):
    """
    Reserved — BYO Pipecat transport.

    `POST /v1/sessions` still rejects `transport.type=pipecat`; use
    `POST /v1/pipecat/sessions` for the Protoface Pipecat video service.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["pipecat"] = "pipecat"


class VideoEncoding(Enum):
    jpeg = "jpeg"
    rgb24 = "rgb24"


class PipecatWebSocketRelayView(BaseModel):
    """
    Short-lived direct media connection details for the Pipecat plugin.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    audio_sample_rate: int
    decoded_video_format: Literal["RGB"]
    media_token: str
    media_url: str
    protocol: str
    supports_audio_output: bool
    type: Literal["websocket"] = "websocket"
    video_encoding: VideoEncoding


class PlanView(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    custom_avatar_slots: int
    extra_avatar_slot_cents: int | None
    extra_credit_unit_micros: int | None
    included_credits: int
    key: str
    max_concurrency: int
    monthly_price_cents: int
    name: str
    session_time_limit_seconds: int


class QualityTier(Enum):
    """
    Output quality tier.
    """

    mock = "mock"
    lite = "lite"
    standard = "standard"
    pro = "pro"


class MaxDurationSeconds1(RootModel[int]):
    root: int = Field(
        ...,
        description="Optional customer-requested hard ceiling on session duration. The API clamps this to the caller's plan limit and returns the effective value on the Session resource.",
        ge=1,
        le=3600,
    )


class SessionFailure(BaseModel):
    """
    Populated when `Session.status == failed`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    code: str = Field(..., description="Stable lower_snake_case subcode.")
    message: str = Field(..., description="Human-readable summary; not stable.")


class SessionStatus(Enum):
    """
    Public session lifecycle.

    Terminal states are `ended`, `failed`, `canceled`. `ending` is the
    graceful-drain state while a worker finishes publishing in-flight frames.
    """

    created = "created"
    queued = "queued"
    starting = "starting"
    running = "running"
    ending = "ending"
    ended = "ended"
    failed = "failed"
    canceled = "canceled"


class SessionUsage(BaseModel):
    """
    Live usage counters embedded in the Session resource.

    Eventually-consistent — lags the latest worker heartbeat by up to
    one interval. Canonical billing data lives in `UsageEvent`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    billable_seconds: int = Field(..., ge=0)
    frames: int = Field(..., ge=0)


class Status(Enum):
    operational = "operational"
    degraded = "degraded"
    outage = "outage"


class StatusComponent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    status: Status


class Status1(Enum):
    """
    Roll-up of all components.
    """

    operational = "operational"
    degraded = "degraded"
    outage = "outage"


class StatusResponse(BaseModel):
    """
    `GET /v1/status` response.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    components: list[StatusComponent]
    status: Status1 = Field(..., description="Roll-up of all components.")
    updated_at: AwareDatetime


class UsageSummary(BaseModel):
    """
    Aggregated usage; returned by `GET /v1/usage`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    billable_seconds: int = Field(
        ...,
        description="Total billable seconds across all sessions in the window.",
        ge=0,
    )
    by_quality: dict[QualityTier, int] | None = Field(
        default=None,
        description="`billable_seconds` per quality tier. Forward-compatible breakdown — additional `by_*` slices may appear over time.",
    )
    period_end: AwareDatetime = Field(
        ...,
        description="Exclusive end of the aggregated window. Matches the `period_end` query argument.",
    )
    period_start: AwareDatetime = Field(
        ...,
        description="Inclusive start of the aggregated window. Matches the `period_start` query argument.",
    )
    sessions: int = Field(
        ...,
        description="Number of sessions that contributed usage in the window.",
        ge=0,
    )


class WebSocketTransportConfig(BaseModel):
    """
    Reserved — raw WebSocket transport. **Not yet available.**

    Listed in the schema so existing clients keep parsing future responses,
    but `POST /v1/sessions` rejects it today with
    `invalid_request` / `code=transport.unsupported`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["websocket"] = "websocket"


class ApiError(BaseModel):
    """
    Concrete error returned inside `ApiErrorEnvelope.error`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    code: str = Field(
        ...,
        description="Stable machine-readable subcode (lower_snake_case). SDKs should switch on this, not `message`.",
    )
    message: str = Field(..., description="Human-readable summary. Not stable; do not parse.")
    param: str | None = Field(
        default=None, description="Offending request field (dot-path), if applicable."
    )
    request_id: str = Field(
        ..., description="Echo of the `X-Request-Id` response header for support."
    )
    type: ErrorType


class ApiErrorEnvelope(BaseModel):
    """
    Wire format for every non-2xx public API response.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    error: ApiError


class Avatar(BaseModel):
    """
    Public Avatar resource returned by `GET /v1/avatars` and `GET /v1/avatars/{id}`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    created_at: AwareDatetime
    default_custom_instructions: str | None = Field(
        default=None,
        description="Preferred managed-conversation instructions for this avatar, when configured.",
    )
    default_voice: str | None = Field(
        default=None,
        description="Preferred conversation voice for this avatar, when configured.",
    )
    failure_reason: str | None = Field(
        default=None,
        description="Human-readable reason the build failed (e.g. `No face detected in source image.`). Only set while `status` is `failed`.",
    )
    id: str = Field(
        ...,
        description="Stable `av_…` avatar id. Platform stock avatars use fixed ids such as `av_stock_001`; customer avatars use generated ids.",
    )
    is_demo: bool = Field(..., description="True for platform stock avatars (e.g. `av_stock_001`).")
    name: str
    object: Literal["avatar"] = "avatar"
    runtime_type: str = Field(
        ..., description="Runtime that serves this avatar (e.g. `mock`, `avtr1`)."
    )
    status: AvatarStatus


class AvatarList(BaseModel):
    """
    Cursor-paginated list of avatars.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[Avatar]
    has_more: bool
    next_cursor: str | None = Field(
        default=None,
        description="Pass as `starting_after` on the next request to continue.",
    )
    object: Literal["list"] = "list"


class PipecatSessionCreateRequest(BaseModel):
    """
    Start request for a Pipecat avatar media session.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    avatar_id: str = Field(..., description="Stable `av_...` avatar id.")
    idle_timeout_seconds: int | None = Field(default=30, ge=1, le=600)
    max_duration_seconds: MaxDurationSeconds | None = None
    metadata: dict[str, str | int | float | bool | None] | None = None
    quality: QualityTier | None = QualityTier.standard
    relay_mode: Literal["websocket"] = "websocket"


class Session(BaseModel):
    """
    Public session resource — what `GET /v1/sessions/{id}` returns.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    avatar_id: str
    created_at: AwareDatetime
    ended_at: AwareDatetime | None = None
    failed_at: AwareDatetime | None = None
    failure: SessionFailure | None = None
    first_frame_at: AwareDatetime | None = Field(
        default=None, description="Set on `session.first_frame`."
    )
    id: str = Field(..., description="`sess_…` prefixed ULID.")
    idle_timeout_seconds: int
    max_duration_seconds: int
    metadata: dict[str, str | int | float | bool | None]
    object: Literal["session"] = "session"
    quality: QualityTier
    started_at: AwareDatetime | None = Field(
        default=None, description="Set when worker emits `session.starting`."
    )
    status: SessionStatus
    transport: LiveKitTransportConfig | WebSocketTransportConfig | PipecatTransportConfig = Field(
        ..., discriminator="type"
    )
    usage: SessionUsage | None = None


class SessionCreateRequest(BaseModel):
    """
    Request body for `POST /v1/sessions`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    avatar_id: str = Field(
        ...,
        description="Stable `av_…` avatar id. Must reference a platform stock avatar or customer avatar the caller's API key can access.",
    )
    idle_timeout_seconds: int | None = Field(
        default=30,
        description="End the session automatically after this many seconds without received audio. Only applies to transports that observe inbound audio; ignored otherwise.",
        ge=1,
        le=600,
    )
    max_duration_seconds: MaxDurationSeconds1 | None = Field(
        default=None,
        description="Optional customer-requested hard ceiling on session duration. The API clamps this to the caller's plan limit and returns the effective value on the Session resource.",
    )
    metadata: dict[str, str | int | float | bool | None] | None = Field(
        default=None,
        description="Customer-owned free-form JSON, <= 8 KB. Keys prefixed with `_avatar.` are managed by Protoface.",
    )
    quality: QualityTier | None = Field(
        default=QualityTier.standard,
        description="Quality tier; drives the billing multiplier.",
    )
    transport: LiveKitTransportConfig | WebSocketTransportConfig | PipecatTransportConfig = Field(
        ...,
        description="Discriminated union of transport configs, keyed by `type`.",
        discriminator="type",
    )


class SessionList(BaseModel):
    """
    Cursor-paginated list of sessions.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[Session]
    has_more: bool
    next_cursor: str | None = Field(
        default=None,
        description="Pass as `starting_after` on the next request to continue.",
    )
    object: Literal["list"] = "list"


class PipecatSessionView(BaseModel):
    """
    Pipecat avatar media session.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    object: Literal["pipecat.session"] = "pipecat.session"
    relay: PipecatWebSocketRelayView
    session: Session
